version: '2'
services:
  tachyon:
    image: ghcr.io/kimusan/tachyon:latest
    ports:
      - 8888:8888
    environment:
      - DEBUG=true
    volumes:
      - tachyon:/var/lib/tachyon
    networks:
      - default
    restart: unless-stopped

  # This provides prometheus metrics for tachyon's php-fpm
  php-fpm-exporter:
    image: hipages/php-fpm_exporter:2.2.0
    ports:
      - 9253:9253
    environment:
      - PHP_FPM_SCRAPE_URI=tcp://tachyon:9000/status
    networks:
      - default

networks:
  default:

volumes:
  tachyon:
    driver: local
