/* Tachyon Webmail (c) Tachyon | Licensed under AGPL v3 */
const fs = require('fs');
const path = require('path');

const ICON_DIR = 'vendors/lucide/icons';
const OUT = 'vendors/lucide/icons.css';

// Icons are drawn with strokes, and currentColor does not resolve inside a
// mask, so the stroke is baked solid here and the colour comes from
// background-color: currentColor on the element instead.
const toDataUri = svg => {
	const cleaned = svg
		.replace(/<!--[\s\S]*?-->/g, '')
		.replace(/\s*\n\s*/g, ' ')
		.replace(/>\s+</g, '><')
		.replace(/currentColor/g, '#000')
		.replace(/\s+class="[^"]*"/g, '')
		.trim();
	// encodeURIComponent escapes far more than a CSS url() needs. Using single
	// quotes inside the SVG and escaping only what actually breaks parsing keeps
	// the file roughly half the size and just as valid.
	return 'data:image/svg+xml,' + cleaned
		.replace(/"/g, "'")
		.replace(/%/g, '%25')
		.replace(/#/g, '%23')
		.replace(/</g, '%3C')
		.replace(/>/g, '%3E')
		.replace(/\s+/g, ' ');
};

const buildIcons = done => {
	const names = fs.readdirSync(ICON_DIR).filter(f => f.endsWith('.svg')).sort();
	const rules = names.map(file => {
		const name = path.basename(file, '.svg'),
			uri = toDataUri(fs.readFileSync(path.join(ICON_DIR, file), 'utf8'));
		// Held in a custom property so the prefixed and unprefixed mask-image in
		// the base rule can share one copy of the URI. Chrome only dropped the
		// -webkit- prefix in 120, so both are still worth emitting.
		return `[data-icon="${name}"]::before,\n.icon-${name}::before { --tachyon-icon: url("${uri}"); }`;
	});

	const css = `/* Generated by tasks/icons.js from ${ICON_DIR}. Do not edit. */
/* Lucide, ISC licensed, see vendors/lucide/LICENSE */

[data-icon]::before,
[class^="icon-"]:not(.icon-spinner)::before,
[class*=" icon-"]:not(.icon-spinner)::before {
\tcontent: "";
\tdisplay: inline-block;
\twidth: 1em;
\theight: 1em;
\tvertical-align: -0.125em;
\tbackground-color: currentColor;
\t-webkit-mask: var(--tachyon-icon) no-repeat center / contain;
\tmask: var(--tachyon-icon) no-repeat center / contain;
}

[data-icon]::before {
\tmargin-right: 0.5em;
}

${rules.join('\n\n')}
`;
	fs.writeFileSync(OUT, css);
	console.log(`[icons] ${names.length} icons -> ${OUT} (${(css.length / 1024).toFixed(1)} KB)`);
	done();
};

exports.buildIcons = buildIcons;
