name: docker-pr

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      env:
        DOCKER_METADATA_PR_HEAD_SHA: 'true'
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=pr
          type=ref,suffix=-{{sha}},event=pr
        labels: |
          org.opencontainers.image.description=Tachyon webmail
          org.opencontainers.image.licenses=AGPLv3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and test (amd64)
      uses: docker/build-push-action@v6
      with:
        context: '.'
        file: ./.docker/release/Dockerfile
        platforms: linux/amd64
        push: false
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test
      run: |
        TAG=$( echo "${{ steps.meta.outputs.tags }}" | head -n1 )
        .docker/release/test/test.sh "$TAG"

    - name: Build check (arm64)
      uses: docker/build-push-action@v6
      with:
        context: '.'
        file: ./.docker/release/Dockerfile
        platforms: linux/arm64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
